In [8]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/Users/shingshing/MyDocuments/HKU/Sem3/DASE7310/Hong-Kong-Equity-Forecasting-Portfolio/data/processed/weekly_features_weekly_v1.csv")
df
#ticker = df['ticker'].unique()

,target_week,ticker,return_lag_1,return_lag_2,return_lag_3,return_lag_4,return_lag_8,return_lag_12,return_lag_24,return_lag_52,...,excess_rolling_mean_26,target,return_lag_1_cs_z,return_lag_4_cs_z,return_lag_12_cs_z,rolling_mean_4_cs_z,rolling_mean_12_cs_z,rolling_mean_26_cs_z,risk_adjusted_mean_4_cs_z,excess_return_lag_1_cs_z
0,2021-01-08,0005.HK,0.011194,-0.023086,-0.012005,-0.048000,0.073487,-0.041336,-0.025711,-0.009106,...,0.001298,0.067651,-0.464513,-1.252005,-1.437464,-0.659508,0.723233,0.058304,-1.000605,-0.464513
1,2021-01-08,0016.HK,0.000000,-0.023415,-0.026591,0.020349,0.039920,-0.003046,-0.043456,0.004219,...,-0.001674,0.070929,-0.669259,0.395979,-0.713064,-0.281256,-0.477046,-0.183196,-0.380420,-0.669259
2,2021-01-08,0066.HK,-0.005740,-0.011351,0.016148,0.012850,0.054430,-0.001294,-0.020460,0.015317,...,-0.000932,0.030023,-0.774254,0.215175,-0.679913,0.090928,-0.140823,-0.122940,0.496655,-0.774254
3,2021-01-08,0700.HK,0.015247,-0.038793,-0.013606,-0.000849,-0.020342,0.032437,0.013436,0.040731,...,0.000397,0.012368,-0.390394,-0.115139,-0.041759,-0.355984,-0.496678,-0.014926,-0.504944,-0.390394
4,2021-01-08,0981.HK,0.166318,-0.037261,-0.099320,0.050000,-0.026971,0.080087,-0.115517,0.025316,...,-0.011939,0.121076,2.372762,1.110900,0.859712,0.698326,0.443008,-1.017543,0.423573,2.372762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2975,2026-09-18,1113.HK,0.011407,0.032272,-0.030854,0.051556,0.013113,-0.012987,0.031847,-0.038633,...,0.003833,0.002739,1.218713,0.044644,0.441776,0.759224,0.271781,0.203196,0.779571,1.218713
2976,2026-09-18,1398.HK,-0.011046,0.033580,-0.004013,0.043266,0.040521,-0.033577,0.051359,-0.020000,...,0.009444,0.005256,0.569515,-0.172984,0.097867,0.727166,0.671599,0.917061,1.003897,0.569515
2977,2026-09-18,1810.HK,-0.073136,0.022286,-0.041351,0.132709,-0.005952,-0.128560,-0.064242,0.028105,...,-0.006186,0.030349,-1.225738,2.175152,-1.488636,0.464281,0.625176,-1.071757,0.120235,-1.225738
2978,2026-09-18,3988.HK,-0.003298,0.086918,0.013624,0.048571,0.049213,-0.039848,0.041152,-0.029148,...,0.013312,0.006617,0.793553,-0.033697,-0.006887,1.765319,1.340080,1.409223,1.654056,0.793553
2979,2026-09-18,9988.HK,-0.023615,-0.033363,-0.073984,0.025855,-0.023091,-0.146806,-0.033442,0.052945,...,-0.004969,-0.014884,0.206108,-0.630073,-1.793410,-1.334729,0.115261,-0.916859,-1.320649,0.206108

In [ ]:
import numpy as np
import pandas as pd
from scipy import stats
from scipy.spatial.distance import jensenshannon

def evaluate_return_similarity(r1, r2, bins=30):
    r1, r2 = np.asarray(r1), np.asarray(r2)
    
    # Non-parametric tests
    ks_stat, ks_pval = stats.ks_2samp(r1, r2)
    emd = stats.wasserstein_distance(r1, r2)
    
    # Discretized density divergence
    grid_range = (min(r1.min(), r2.min()), max(r1.max(), r2.max()))
    p, _ = np.histogram(r1, bins=bins, range=grid_range, density=True)
    q, _ = np.histogram(r2, bins=bins, range=grid_range, density=True)
    js_div = jensenshannon(p + 1e-10, q + 1e-10)**2
    
    # Moment tests
    _, t_pval = stats.ttest_ind(r1, r2, equal_var=False)
    _, lev_pval = stats.levene(r1, r2)
    
    return pd.Series({
        "KS_Statistic": ks_stat,
        "KS_p_value": ks_pval,
        "Wasserstein_Distance": emd,
        "JS_Divergence": js_div,
        "Mean_Diff_p_value": t_pval,
        "Vol_Diff_p_value": lev_pval
    })

def fun(stock,t):
    before = df[(df['target_week'] <= t) * (df['ticker'] == stock)].return_lag_1
    after = df[(df['target_week'] > t) * (df['target_week'] <= "2026-01-01") * (df['ticker'] == stock)].return_lag_1


    # print(before.describe())
    # print(after.describe())
    # plt.hist(before, color='gray',density=True)
    # plt.hist(after,density=True)
    print(evaluate_return_similarity(before,after))
    # plt.show()

:

:

In [2]:
for tick in ticker:
    print("="*5+tick+"="*5)
    fun(tick, "2025-01-01")

=====0005.HK=====

NameError: name 'fun' is not defined

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import ks_2samp, wasserstein_distance

# 假設 df_returns 的 Index 為 DatetimeIndex，欄位為股票代號
def plot_rolling_regime_shift(df_returns, baseline_end='2021-12-31', window=52):
    plt.figure(figsize=(12, 6), dpi=150)
    
    for ticker, color in zip(['0005.HK', '1810.HK'], ['navy', 'crimson']):
        series = df_returns[ticker].dropna()
        baseline = series.loc[:baseline_end]
        
        w_dists = []
        dates = []
        
        # 逐週動態滾動計算 Wasserstein Distance
        for i in range(window, len(series)):
            current_window = series.iloc[i-window:i]
            w_dist = wasserstein_distance(current_window, baseline)
            
            w_dists.append(w_dist)
            dates.append(series.index[i])
            
        df_plot = pd.Series(w_dists, index=dates)
        plt.plot(df_plot, label=f'{ticker} (Rolling Wasserstein Distance)', color=color, linewidth=2)

    # 圖表格式調整
    plt.axhline(y=0.012, color='gray', linestyle='--', label='Regime Shift Warning Threshold')
    plt.title('Dynamic Regime Shift Drift (2020-01-01 to 2025-08-31)', fontsize=14, fontweight='bold')
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Wasserstein Distance vs. 2020-2021 Baseline ($W_1$)', fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.legend(loc='upper left', frameon=True)
    plt.tight_layout()
    plt.show()


plot_rolling_regime_shift(df_weekly_returns)

NameError: name 'df_weekly_returns' is not defined

,target_week,ticker,return_lag_1,return_lag_2,return_lag_3,return_lag_4,return_lag_8,return_lag_12,return_lag_24,return_lag_52,...,excess_rolling_mean_26,target,return_lag_1_cs_z,return_lag_4_cs_z,return_lag_12_cs_z,rolling_mean_4_cs_z,rolling_mean_12_cs_z,rolling_mean_26_cs_z,risk_adjusted_mean_4_cs_z,excess_return_lag_1_cs_z
0,2021-01-08,0005.HK,0.011194,-0.023086,-0.012005,-0.048000,0.073487,-0.041336,-0.025711,-0.009106,...,0.001298,0.067651,-0.464513,-1.252005,-1.437464,-0.659508,0.723233,0.058304,-1.000605,-0.464513
1,2021-01-08,0016.HK,0.000000,-0.023415,-0.026591,0.020349,0.039920,-0.003046,-0.043456,0.004219,...,-0.001674,0.070929,-0.669259,0.395979,-0.713064,-0.281256,-0.477046,-0.183196,-0.380420,-0.669259
2,2021-01-08,0066.HK,-0.005740,-0.011351,0.016148,0.012850,0.054430,-0.001294,-0.020460,0.015317,...,-0.000932,0.030023,-0.774254,0.215175,-0.679913,0.090928,-0.140823,-0.122940,0.496655,-0.774254
3,2021-01-08,0700.HK,0.015247,-0.038793,-0.013606,-0.000849,-0.020342,0.032437,0.013436,0.040731,...,0.000397,0.012368,-0.390394,-0.115139,-0.041759,-0.355984,-0.496678,-0.014926,-0.504944,-0.390394
4,2021-01-08,0981.HK,0.166318,-0.037261,-0.099320,0.050000,-0.026971,0.080087,-0.115517,0.025316,...,-0.011939,0.121076,2.372762,1.110900,0.859712,0.698326,0.443008,-1.017543,0.423573,2.372762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2975,2026-09-18,1113.HK,0.011407,0.032272,-0.030854,0.051556,0.013113,-0.012987,0.031847,-0.038633,...,0.003833,0.002739,1.218713,0.044644,0.441776,0.759224,0.271781,0.203196,0.779571,1.218713
2976,2026-09-18,1398.HK,-0.011046,0.033580,-0.004013,0.043266,0.040521,-0.033577,0.051359,-0.020000,...,0.009444,0.005256,0.569515,-0.172984,0.097867,0.727166,0.671599,0.917061,1.003897,0.569515
2977,2026-09-18,1810.HK,-0.073136,0.022286,-0.041351,0.132709,-0.005952,-0.128560,-0.064242,0.028105,...,-0.006186,0.030349,-1.225738,2.175152,-1.488636,0.464281,0.625176,-1.071757,0.120235,-1.225738
2978,2026-09-18,3988.HK,-0.003298,0.086918,0.013624,0.048571,0.049213,-0.039848,0.041152,-0.029148,...,0.013312,0.006617,0.793553,-0.033697,-0.006887,1.765319,1.340080,1.409223,1.654056,0.793553
2979,2026-09-18,9988.HK,-0.023615,-0.033363,-0.073984,0.025855,-0.023091,-0.146806,-0.033442,0.052945,...,-0.004969,-0.014884,0.206108,-0.630073,-1.793410,-1.334729,0.115261,-0.916859,-1.320649,0.206108

: